spring:
  datasource:
    #driverClassName: 'org.postgresql.Driver'
    maxActive: '20'
    maxIdle: '15'
    minIdle: '2'
    initialSize: '10'
    removeAbandoned: false
    sql-script-encoding: UTF-8
    #url: ${JDBC_DATABASE_URL:}
    url: 'jdbc:h2:file:~/votacaodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE'
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  devtools:
    add-properties: true
  profiles:
    active: production
server:
  error:
    include-message: never
    include-stacktrace: never
  #port: ${PORT:8080}
logging:
  level:
    org:
      springframework: INFO
votacao:
  tempo:
    sessao:
      minutos: '30'
  eleitor:
    persistir:
      permissao:
        voto: true
  pauta:
    permitir:
      duplicidade:
        nome: true